print("====================================")
print("    PERSONAL PROFILE GENERATOR")
print("====================================")

name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
college = input("Enter your college: ")
course = input("Enter your course:")
dream = input("What is your dream career? ")
anime = input("Favorite anime: ")
game = input("Favorite game:")

print("\n========== YOUR PROFILE ==========")
print("👤 Name:", name)
print("🎂 Age:", age)
print("🏙️ City:", city)
print("🏫 College:", college)
print("📚 Course:", course)
print("💼 Dream Career:", dream)
print("🎌 Favorite Anime:", anime)
print("🎮 Favorite Game:", game)
print("==================================")
print("Thank you for using my first project!")